name: CI
on: [pull_request]
jobs:
  tests:
    name: "Test (python: ${{ matrix.python-version }}, sphinx: ${{ matrix.sphinx-version }})"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: [ "3.8", "3.9"]  # No "3.10", as nose seem to have problems with it
        sphinx-version: ['5.0']
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Nox Dependencies
        run: |
          python -m pip install poetry nox nox-poetry
      - name: Run Tests
        run: nox --non-interactive --session "tests-${{ matrix.python-version }}(sphinx='${{ matrix.sphinx-version }}')" -- --full-trace

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Upgrade Pip
        run: |
          python -m pip install -U pip
      - name: Install Nox Dependencies
        run: |
          python -m pip install poetry nox nox-poetry
      - uses: pre-commit/action@v3.0.0

  linkcheck:
    name: Docs-Linkcheck
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Upgrade Pip
        run: |
          python -m pip install -U pip
      - name: Install Nox Dependencies
        run: |
          python -m pip install poetry nox nox-poetry
      - name: Run LinkCheck
        run: nox --non-interactive --session linkcheck -- --full-trace
